server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bankDb;
    username: med
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info
